### ISSUE TITLE
Cannot convert 'string' to 'enum nnp_status'

### ISSUE THREAD

**Issue by jonahfriedman** [szagoruyko/nnpack.torch#1]
Hello,

Thank you very much for providing this. I'm having trouble getting it working on Linux. I built all the prerequisites, and the shared library is available, and when I add the line,

`require 'nnpack'`

to an otherwise working lua script, I get this:

```
/home/torch/torch/install/bin/luajit: /home/torch/torch/install/share/lua/5.1/trepl/init.lua:384: /home/torch/torch/install/share/lua/5.1/nnpack/init.lua:10: cannot convert 'string' to 'enum nnp_status'
stack traceback:
        [C]: in function 'error'
        /home/torch/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        neural_style_nnpack.lua:5: in main chunk
        [C]: in function 'dofile'
        ...orch/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064d0
```

Any help or insight would be greatly appreciated, and thank you for providing this.

**Comment by szagoruyko** [comment]
do you have a compatible CPU? can you add a print or stop in the debugger in this line, I don't see why it errors out

**Comment by jonahfriedman** [comment]
Ah, that was silly of me. My CPU is not compatible, I thought it would be without checking first. Thanks for your help.

**Comment by szagoruyko** [comment]
it actually checks, looks like there is bug in error handling that I need to fix, thanks for reporting.

**Comment by jonahfriedman** [comment]
Ah, no problem. I hope to use this soon on a different machine.
