### ISSUE TITLE
SpatialConvolution_forward_single test failing

### ISSUE THREAD

**Issue by floringogianu** [szagoruyko/nnpack.torch#2]
I am on OSX El Capitan, clang-602.0, `nnpack` compiled just fine and I was able to convert a network to the `nnpack` backend. However tests are failing:

```
» th test.lua
Running 3 tests
1/3 SpatialConvolution_forward_batch .................................... [PASS]
2/3 SpatialConvolution_forward_single ................................... [WAIT][1]    22043 segmentation fault  th test.lua
```

I was able to forward only a batch input through my model, but not an individual example, basically confirming the results of the test.

**Comment by szagoruyko** [comment]
I updated it and forgot to push - please pull and try again, I have just pushed https://github.com/szagoruyko/nnpack.torch/commit/f9875300b4f941110000b0877436af0ed548c9a3

btw in my experience nnpack is several times slower than SpatialConvolutionMM on macbooks.

**Comment by floringogianu** [comment]
Thank you for the fast reply, I can confirm the tests pass now. I was only able to `require 'nnpack'` this time after I edited the last lines of `ffi.lua` in https://github.com/szagoruyko/nnpack.torch/commit/f9875300b4f941110000b0877436af0ed548c9a3

**Comment by szagoruyko** [comment]
thanks, fixed in https://github.com/szagoruyko/nnpack.torch/commit/09af16f4b79e47357762fc31e7049a5d3f2d5f9c
