### ISSUE TITLE
Typos in pad sizes?

### ISSUE THREAD

**Issue by mikowals** [szagoruyko/nnpack.torch#6]
`{top = padH, bottom = padH, left = padW, right = padH}` should  have `right=padW` I think.

https://github.com/szagoruyko/nnpack.torch/blob/master/functional.lua#L16
https://github.com/szagoruyko/nnpack.torch/blob/master/functional.lua#L65
https://github.com/szagoruyko/nnpack.torch/blob/master/functional.lua#L85

**Comment by szagoruyko** [comment]
fixed via https://github.com/szagoruyko/nnpack.torch/commit/336731f9a9215a681d4274377b7a629d4693293e, thanks
